apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AppName }}-service
  namespace: {{ .Values.NameSpace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.AppName }}
  ports:
  - port: {{ .Values.MariadbDbPort }}
    targetPort: {{ .Values.MariadbDbPort }}
    protocol: TCP